version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - ENV=development
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - qdrant
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CREATION_ON_FILE_ABSENCE=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  qdrant_data: