version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app:/app/app
      - ./dns_config:/app/dns_config
      - ./dns_test.sh:/app/dns_test.sh
    env_file:
      - .env
    environment:
      - ENV=development
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    # Docker now supports multiple extra_hosts entries
    # We're using Face++ API now so no need for specific host entries
    # Add Google DNS servers explicitly to ensure reliable resolution
    dns_search: .
    dns_opt:
      - timeout:2
      - attempts:5
      - rotate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/diagnostics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - qdrant
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_CREATION_ON_FILE_ABSENCE=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    # Enable DNS resolution and internet access
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  qdrant_data: